### PR TITLE
Rework Blueprints.lua

### PR DESCRIPTION
**Pull request by Azraeel**
This Pull Request removes many alterations of the Blueprints 

Why? This makes sure we have a more clearer understanding of the balance within the .bp files themselves.

Many of these changes can be added back in the future if deemed so however We should only be adding wholesale blueprints.lua changes only when/if we agree that an Entire Layer (i.e Land, Air, Naval), Category (Tech3), or a entire bp variable (within a Layer or Category) needs to be standardized/changed.

### CODE REVIEW

**Comment by loudpatches** [comment]
I don't know what's changed, even based off of the diff.  It looks like formatting changes and positional changes all over (kind of obfuscates the meaningful changes).  This is still a mess IMO, with a bunch of loops doing too much.  I would personally prefer it decomposed further, to establish which transforms are being done in a pipeline.

**Comment by Azraeel** [comment]
@loudpatches I 100% Agree on readability, I just want to make sure people like the removal of changes. We can worry about about the decomposition of this later. I understand which transforms are being done and will write them all down in a comment section in Blueprints.lua.

**Comment by Azraeel** [comment]
Actually, since the BP Clobber will probably stay eitherway I'll just reformat it right now.

**Comment by Azraeel** [comment]
This should be ready to go, I tested for errors and such I didnt see any and all units did shoot at each other.

**Pull request merged**
